QUIZZ/Voltaire/Controllers/DifficultesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Voltaire.Models;

namespace Voltaire.Controllers
{
    [Authorize]
    public class DifficultesController : Controller
    {
        //context de ma base de donnee
        private VoltaireContext db = new VoltaireContext();
        //context par defaut de aspnet
        private static ApplicationDbContext dbu = new ApplicationDbContext();
        //permet d acceder a la table user
        private UserManager<ApplicationUser> manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dbu));

        // GET: Difficultes

        public ActionResult Index()
        {
            //utilisateur courant
            var currentUser = manager.FindById(User.Identity.GetUserId());
            Session["email"] = currentUser.Email;
            string em = currentUser.Email;
            try
            {
                // si l email n est pas trouve ds la bd on initilise les tables
                string emailuser = db.StatUsers.Where(x => x.email == em).FirstOrDefault().email;
            }
            catch (Exception e)
            {
                var te = from c in db.Questions
                    from a in db.Niveaux
                    where c.NiveauId == a.id
                    select new {Question = c, Niveau = a};
                var q = te.DistinctBy(x => x.Question.id_regle).ToList();
                var pop = te.DistinctBy(x => x.Question.NiveauId).ToList();
                
                foreach (var item in pop)
                {
                    ScoreNiveau n = new ScoreNiveau();
                   n.usr_email = em;
                   n.id_niveau = item.Question.NiveauId;
                   n.id_diff = item.Niveau.DifficulteId;
                   n.score_niveau = 0;
                   db.ScoreNiveaus.Add(n);
                   db.SaveChanges();
                }
                foreach (var item in q)
                {
              

                    StatUser u = new StatUser();
                    u.email = em;
                    u.score_regle = 0;
                    u.id_regle = item.Question.id_regle;
                    u.id_niveau = item.Question.NiveauId;
                    u.id_difficulte = item.Niveau.DifficulteId;
                    db.StatUsers.Add(u);
                    db.SaveChanges();
                }
            }

            //selectionner les difficultes 
            List<Difficulte> difficultes = db.Difficultes.ToList();

            return View(difficultes);
        }


        // GET: Difficultes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Difficulte difficulte = db.Difficultes.Find(id);
            if (difficulte == null)
            {
                return HttpNotFound();
            }
            return View(difficulte);
        }

        // GET: Difficultes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Difficultes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,module,description_diff")] Difficulte difficulte)
        {
            if (ModelState.IsValid)
            {
                db.Difficultes.Add(difficulte);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(difficulte);
        }

        // GET: Difficultes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Difficulte difficulte = db.Difficultes.Find(id);
            if (difficulte == null)
            {
                return HttpNotFound();
            }
            return View(difficulte);
        }

        // POST: Difficultes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,module,description_diff")] Difficulte difficulte)
        {
            if (ModelState.IsValid)
            {
                db.Entry(difficulte).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(difficulte);
        }

        // GET: Difficultes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Difficulte difficulte = db.Difficultes.Find(id);
            if (difficulte == null)
            {
                return HttpNotFound();
            }
            return View(difficulte);
        }

        // POST: Difficultes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Difficulte difficulte = db.Difficultes.Find(id);
            db.Difficultes.Remove(difficulte);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QUIZZ/Voltaire/Controllers/NiveauxController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Voltaire.Models;

namespace Voltaire.Controllers
{
    public class NiveauxController : Controller
    {
        private VoltaireContext db = new VoltaireContext();

        [HttpPost]
        // Post: Niveaux
        
        public ActionResult Index(int diff)
        {
            Session["diff"] = diff;
          
            List<Niveau> niveaux = db.Niveaux.Where(s => s.DifficulteId == diff).ToList();
            Session["ere"] = niveaux;
            string em = (string)Session["email"];
            List<int> v = db.ScoreNiveaus.Where(p => p.id_diff == diff & p.usr_email.Equals(em)).Select(s=>s.score_niveau).ToList();
            List<int> l = new List<int>();
            for (int i=0;i<v.Count;i++){
                if (i == 0)
                {
                    l.Add(1);
                }
                else
                {
                    if (v[i - 1] > 5)
                    {
                        l.Add(1);
                    }
                    else
                    {
                        l.Add(0);
                    }
                }
            }
            Session["list"] = l;
            Session["listDesScores"] = v;

            return View(niveaux);
        }

        public ActionResult Renit(int diff)
        {
            string em = (string)Session["email"];
            var query = (from u in db.ScoreNiveaus where u.usr_email.Equals(em) & u.id_diff == diff select u);
            int c = query.Count();
            foreach (ScoreNiveau ord in query)
            {
                ord.score_niveau = 0;
      
            }
            db.SaveChanges();
            var query2 = (from u in db.StatUsers where u.email.Equals(em) select u);
            foreach (StatUser ord in query2)
            {
                ord.score_regle = 0;

            }
            db.SaveChanges();
            List<int> l2 = new List<int>();List<int> l1 = new List<int>();
            for (int i = 0; i < c + 1; i++)
            {
                l2.Add(0);
                l1.Add(0);
            }
            l1[0] = 1;
            Session["list"] = l1;
            Session["listDesScores"] = l2;
            List<Niveau> l = Session["ere"] as List<Niveau>;
            return View("Index",l);
        }
        // GET: Niveaux/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Niveau niveau = db.Niveaux.Find(id);
            if (niveau == null)
            {
                return HttpNotFound();
            }
            return View(niveau);
        }

        // GET: Niveaux/Create
        public ActionResult Create()
        {
            ViewBag.DifficulteId = new SelectList(db.Difficultes, "id", "module");
            return View();
        }

        // POST: Niveaux/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,titre_niv,description_niv,DifficulteId")] Niveau niveau)
        {
            if (ModelState.IsValid)
            {
                db.Niveaux.Add(niveau);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DifficulteId = new SelectList(db.Difficultes, "id", "module", niveau.DifficulteId);
            return View(niveau);
        }

        // GET: Niveaux/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Niveau niveau = db.Niveaux.Find(id);
            if (niveau == null)
            {
                return HttpNotFound();
            }
            ViewBag.DifficulteId = new SelectList(db.Difficultes, "id", "module", niveau.DifficulteId);
            return View(niveau);
        }

        // POST: Niveaux/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,titre_niv,description_niv,DifficulteId")] Niveau niveau)
        {
            if (ModelState.IsValid)
            {
                db.Entry(niveau).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DifficulteId = new SelectList(db.Difficultes, "id", "module", niveau.DifficulteId);
            return View(niveau);
        }

        // GET: Niveaux/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Niveau niveau = db.Niveaux.Find(id);
            if (niveau == null)
            {
                return HttpNotFound();
            }
            return View(niveau);
        }

        // POST: Niveaux/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Niveau niveau = db.Niveaux.Find(id);
            db.Niveaux.Remove(niveau);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QUIZZ/Voltaire/Views/Niveaux/Create.cshtml
@model Voltaire.Models.Niveau

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Niveau</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.titre_niv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titre_niv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titre_niv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description_niv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description_niv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description_niv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DifficulteId, "DifficulteId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DifficulteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DifficulteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner a la liste ", "Index", "Niveaux", new { diff = @TempData["diff"]},null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QUIZZ/Voltaire/Views/Niveaux/Delete.cshtml
@model Voltaire.Models.Niveau

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Niveau</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Difficulte.module)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Difficulte.module)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.titre_niv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titre_niv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description_niv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description_niv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QUIZZ/Voltaire/Views/Niveaux/Details.cshtml
@model Voltaire.Models.Niveau

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Niveau</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Difficulte.module)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Difficulte.module)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.titre_niv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titre_niv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description_niv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description_niv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QUIZZ/Voltaire/Views/Niveaux/Edit.cshtml
@model Voltaire.Models.Niveau

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Niveau</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.titre_niv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titre_niv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titre_niv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description_niv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description_niv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description_niv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DifficulteId, "DifficulteId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DifficulteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DifficulteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QUIZZ/Voltaire/Views/Niveaux/Index.cshtml
@model IEnumerable<Voltaire.Models.Niveau>
@{
    Layout = "~/views/shared/_LayN.cshtml";
}
@{
    ViewBag.Title = "Index";
    List<int> l = (List<int>) Session["list"];
    List<int> ls = (List<int>)Session["listDesScores"];
    int i = 0;
}
<script>
    function preventBack(){window.history.forward();}
    setTimeout("preventBack()", 0);
    window.onunload=function(){null};
</script>


@*<p>
    @Html.ActionLink("Retourner a la liste ", "Index", "Difficultes")
</p>*@

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">    
    <!-- The Grid -->
    <div class="w3-row">
        <!-- Left Column -->
        <div class="w3-col m3">
            <!-- Profile -->
            <div class="w3-card-2 w3-round w3-white">
                <div class="w3-container w3-padding">
                    <h4 class="w3-center">Ayoub Bennouna</h4>
                    <p class="w3-center "><img src="~/Content/img/3.png" style="height:106px;width:106px" alt="Avatar"></p>
                    <hr>
                    <p><em class="fa fa-pencil fa-fw w3-margin-right w"></em>Etudiant</p>
                    <p><em class="fa fa-home fa-fw w3-margin-right w"></em> Rabat,Agdal</p>
                    <p><em class="fa fa-birthday-cake fa-fw w3-margin-right w"></em> Mai 18, 1995</p>
                </div>
            </div>
            <br>
      
            <!-- Accordion -->
            <div class="w3-card-2 w3-round">
                <div class="w3-white">
                    <div id="Demo1" class="w3-hide w3-container">
                        <p>Some text..</p>
                    </div>
                    <div id="Demo2" class="w3-hide w3-container">
                        <p>Some other text..</p>
                    </div>
     
                </div>      
            </div>
            <br>
      
            <!-- Interests --> 
            <div class="w3-card-2 w3-round w3-white w3-hide-small"></div>
            <br>
      
            <!-- Alert Box --><!-- End Left Column -->
        </div>
    
        <!-- Middle Column -->
        <div class="w3-col m8">
    
            <div class="w3-row-padding">
                <form id="f1"action="/Niveaux/Renit/" method="post">
        
                    <input type="hidden" name="diff" value="@Session["diff"]" />
                     
                </form>
                <div class="w3-card-4 w3-round w3-white w3-padding e w3-padding-24 w3-margin-left">
                    <div class="w3-container w3-padding e">
                        <span style="font-size: 30px;  "  class="w3-padding w3-left i"><strong class="w3-padding">MES EVALUATIONS CERTIFICATIVES </strong></span>
                      
                        <button type="submit" style="margin-top:12px;" form="f1" class="w3-button i w3-right w3-padding w3-white "><em class="fa fa-refresh "></em> <strong>Réinitialiser</strong></button> 
                    </div>
                    <div class=" "><br>
       
                        <table class=" w3-card-4 w3-table w3-border w3-bordered w3-centered w3-hoverable  w3-xlarge">
                            @*<tr>
      
                                <th>
                                    @Html.DisplayNameFor(model => model.titre_niv)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.description_niv)
                                </th>
                                <th></th>
                            </tr>*@

                            @foreach (var item in Model) {
                                <tr>
    
                                    <td>
                                        @{
                                            if (l[i] == 1)
                                            {
                                                <form action="/Questions/Select/" method="post">
                                                    <input type="hidden" name="niv" value="@item.id"/>
                                                    <button class="w3-button w3-left" type="submit"><strong>@item.titre_niv</strong></button>
                                                </form>
                                            }
                                            else
                                            {

                                                <div class="w3-button w3-left" style="color: gray">@Html.Label(@item.titre_niv)</div>
                                            }

                                        }
                
                
                                    </td>
                                    <td>
                                        <span class="w3-right"> @(ls[i] * (100 / 8)) <span>%</span></span>
                                        
                                        @{
                                            i++;
                                        }
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.description_niv)
                                    </td>
                       
                                </tr>
                            }
                        </table> 
                    </div>
                </div>
        
            </div>
      
    
            <!-- End Middle Column -->
        </div>
    
        <!-- Right Column -->
        <div class="w3-col m2">
            <div class="w3-card-2 w3-round w3-white w3-center"></div>
            <br>
            <br>
            <!-- End Right Column -->
        </div>
    
        <!-- End Grid -->
    </div>

    <!-- End Page Container -->
</div>
<br>