QUIZZ/Voltaire/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Voltaire.Models
{
    public class Question
    {
        public int id { get; set; }
        public string enonce { get; set; }
        public string correction { get; set; }
        public int id_regle { get; set; }
        public string regle { get; set; }
        public string explication { get; set; }
        public string phrasecorrecte { get; set; }

        public Niveau Niveau { get; set; }
        public int NiveauId { get; set; }

    }
}

QUIZZ/Voltaire/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Voltaire.Models;

namespace Voltaire.Controllers
{
    public class QuestionsController : Controller
    {
        private VoltaireContext db = new VoltaireContext();



        [HttpPost]
        // Post: Questions
        public ActionResult Index(string niv)
        {

            TempData["niv"] = niv;
            List<Question> questions = db.Questions.Where(s => s.Niveau.titre_niv == niv).ToList();

            return View(questions);
        }

        public ActionResult Select(int niv)
        {
            Session["scoreniveau"] = 0;
            Session["scoreregle"] = 0;
            Session["niv"] = niv;
            var te = (from qa in db.StatUsers where qa.id_niveau== niv & qa.score_regle==0 select qa.id_regle);
            List<int> po = te.ToList();
            var qu = (from q in db.Questions where q.NiveauId == niv & po.Contains(q.id_regle) select q);
            int a = qu.ToList().Last().id;
            Session["last"] = a;
         
            var questions = qu.ToList().FirstOrDefault();
            string e = questions.enonce;
            @ViewBag.id = questions.id;

            String[] enonc = e.Split(' ');
            return View(enonc);

        }
        public ActionResult Suivant(int id, int niv)
        {
            @ViewBag.id = id;
            int difff = db.Niveaux.Where(o => o.id == niv).FirstOrDefault().DifficulteId;
            string diffe = db.Difficultes.Where(v => v.id == difff).FirstOrDefault().module;
            int maxid = db.Questions.Where(p => p.NiveauId == niv).Max(i => i.id);
            if (id > maxid)
            {
                return RedirectToAction("Index", "Niveaux", new { diff = diffe });
            }
            else
            {
                var questions = (from q in db.Questions where q.id == id && q.NiveauId == niv select q).ToList().FirstOrDefault();
                string e = questions.enonce;
                @ViewBag.id = id;
                String[] enonc = e.Split(' ');
                return View(enonc);
            }
        }

        public PartialViewResult Check(int id, string reponse)
        {

            //je selectionne id de la regle courante 
            int idRegle = db.Questions.FirstOrDefault(x => x.id == id).id_regle;
            //je selectionne nbr de question de la regle courante 
            int nbrQuestionRegle = db.Questions.Count(x => x.id_regle == idRegle);
            //je selectionne id de la premiere question de la regle courante 
            int premiereQuestIdRegleId = db.Questions.FirstOrDefault(x => x.id_regle == idRegle).id;
            @ViewBag.reg = idRegle;
            @ViewBag.next = id + 1;
            @ViewBag.count = nbrQuestionRegle;
            //je selectionne la question a checker
            var reponses = db.Questions.Where(q => q.id == id).ToList().FirstOrDefault();
            //je recupere la correction
            string r = reponses.correction;
            ViewBag.phrasecorrecte = reponses.phrasecorrecte;
            ViewBag.explication = reponses.explication;
            ViewBag.regle = reponses.regle;
            int y = (int)Session["niv"];

            int nbrQuestionNiveau = db.Questions.Count(x => x.NiveauId == y);

            //je compare la correction a la reponse de l utilisateur
            if (r.Equals(reponse))
            {
                @ViewBag.message = "bravo";
                //percentage de la question
                @ViewBag.s = 100 / nbrQuestionRegle;
                //je stocke le score de la regle courante 
                Session["scoreregle"] = (int)Session["scoreregle"] + 1;
                Session["scoreniveau"] = (int)Session["scoreniveau"] + 1;

            }
            else
            {
                @ViewBag.message = "erreur";

            }

            //je recupere l email de l utilisateur courant
            string em = (string)Session["email"];
            //je recupere le user correspondant a cet email et dont la regle est courante
            var user = (from u in db.StatUsers where u.email.Equals(em) && u.id_regle == idRegle select u).FirstOrDefault();
            var usern = (from u in db.ScoreNiveaus where u.usr_email.Equals(em) & u.id_niveau == y select u).FirstOrDefault();


            int v = (int)Session["last"];
            if (id == v)
            {
                int g = (int)Session["scoreniveau"];
                usern.score_niveau = g;
                db.SaveChanges();
                Session["scoreniveau"] = 0;


            }
            ViewBag.score = user.score_regle;
            ViewBag.email = em;
            ViewBag.i = id;
            ViewBag.p = premiereQuestIdRegleId;
            ViewBag.g = premiereQuestIdRegleId + nbrQuestionRegle - 1;
            //si on arrive a la derniere question de la regle courante et le score et de 100 alors on stock le score ds StatUser
            int a = nbrQuestionRegle + premiereQuestIdRegleId - 1;
            if (id == a)
            {

                if ((int)Session["scoreregle"] == nbrQuestionRegle)
                {

                    user.score_regle = 100;
                    db.SaveChanges();
                    Session["scoreregle"] = 0;
                } 
                else
                {
                    Session["scoreregle"] = 0;
                }

            }

            return PartialView("check");
        }

        public ActionResult ModalPopUp()
        {
            return View();
        }
        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            ViewBag.NiveauId = new SelectList(db.Niveaux, "id", "titre_niv");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,enonce,correction,regle,phrasecorrecte,NiveauId")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.NiveauId = new SelectList(db.Niveaux, "id", "titre_niv", question.NiveauId);
            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.NiveauId = new SelectList(db.Niveaux, "id", "titre_niv", question.NiveauId);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,enonce,correction,regle,phrasecorrecte,NiveauId")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NiveauId = new SelectList(db.Niveaux, "id", "titre_niv", question.NiveauId);
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QUIZZ/Voltaire/Views/Questions/Create.cshtml
@model Voltaire.Models.Question

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.enonce, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.enonce, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.enonce, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.correction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.correction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.correction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.regle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.regle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.regle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phrasecorrecte, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phrasecorrecte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phrasecorrecte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NiveauId, "NiveauId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NiveauId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NiveauId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QUIZZ/Voltaire/Views/Questions/Delete.cshtml
@model Voltaire.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Niveau.titre_niv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Niveau.titre_niv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enonce)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enonce)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.correction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.correction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.regle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.regle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phrasecorrecte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phrasecorrecte)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QUIZZ/Voltaire/Views/Questions/Details.cshtml
@model Voltaire.Models.Question

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Niveau.titre_niv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Niveau.titre_niv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enonce)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enonce)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.correction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.correction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.regle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.regle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phrasecorrecte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phrasecorrecte)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QUIZZ/Voltaire/Views/Questions/Edit.cshtml
@model Voltaire.Models.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.enonce, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.enonce, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.enonce, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.correction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.correction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.correction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.regle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.regle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.regle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phrasecorrecte, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phrasecorrecte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phrasecorrecte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NiveauId, "NiveauId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NiveauId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NiveauId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QUIZZ/Voltaire/Views/Questions/Index.cshtml
@model IEnumerable<Voltaire.Models.Question>


@{
    ViewBag.Title = "Index";
}

<h2>Liste des questions du @TempData["niv"]</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.enonce)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.correction)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.regle)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
    
            <td>
                @Html.DisplayFor(modelItem => item.enonce)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.correction)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.regle)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Retourner a la liste ", "Index", "Niveaux",new {diff=@TempData["diff"]}, null)
</p>

QUIZZ/Voltaire/Views/Questions/ModalPopUp.cshtml
@{  
    ViewBag.Title = "Satyaprakash Bootstrap PopUp";  
}  
  
<title>@ViewBag.Title</title>  
  

QUIZZ/Voltaire/Views/Questions/Select.cshtml
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">


    function disablelink() {
    
        $(".b").removeAttr("href");

    };

</script>

@model String[]

@{
    Layout = "~/views/shared/_LayQ.cshtml";
}

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">    
    <!-- The Grid -->
    <div class="w3-row">
        <!-- Left Column -->
        <div class="w3-col m3">
            <!-- Profile -->
            <div class="w3-card-2 w3-round w3-white">
                <div class="w3-container w3-padding">
                    <h4 class="w3-center">Ayoub Bennouna</h4>
                    <p class="w3-center"><img src="~/Content/img/3.png" style="height:106px;width:106px" alt="Avatar"></p>
                    <hr>
                    <p><em class="fa fa-pencil fa-fw w3-margin-right w"></em>Etudiant</p>
                    <p><em class="fa fa-home fa-fw w3-margin-right w"></em> Rabat,Agdal</p>
                    <p><em class="fa fa-birthday-cake fa-fw w3-margin-right w"></em> Mai 18, 1995</p>
                </div>
            </div>
            <br>
      
            <!-- Accordion -->
            <div class="w3-card-2 w3-round">
                <div class="w3-white">
                    <div id="Demo1" class="w3-hide w3-container">
                        <p>Some text..</p>
                    </div>
                    <div id="Demo2" class="w3-hide w3-container">
                        <p>Some other text..</p>
                    </div>
     
                </div>      
            </div>
            <br>
      
            <!-- Interests --> 
            <div class="w3-card-2 w3-round w3-white w3-hide-small"></div>
            <br>
      
            <!-- Alert Box --><!-- End Left Column -->
        </div>
    
        <!-- Middle Column -->
        <div class="w3-col m8">
    
            <div class="w3-row-padding">
        
                <div class="w3-card-4 w3-round w3-white w3-padding e  w3-margin-left w3-center">
                    <br>
                    <br>
                    <br>
@foreach (var mot in Model)
{
    <span class="w3-xlarge b ">@mot</span>
}

                    <br/>
                    <br/>
                    <hr/>
                    <div id="cor"></div>
              
                        @for (int i = 0; i < 6; i = i + 2)
                        {

                          
                                <div class="w3-xlarge b">
                                    @Ajax.ActionLink(@Model[i], "Check", "Questions", new { id = @ViewBag.id, reponse = @Model[i] }, new AjaxOptions()
                                    {
                                        HttpMethod = "GET",
                                        UpdateTargetId = "cor",
                                        InsertionMode = InsertionMode.Replace,

                                        OnComplete = "disablelink"
                                    }, new
                                    {
                                        @class = "c w3-button  w3-round-large w3-margin",
                                        @style = "text-decoration: none;width:200px"
                                    })
                                </div>
                               
                           

                     

                        }
             
                        @*@foreach(var mot in Model)
            {

                <div class="w3-xlarge b">@Ajax.ActionLink(@mot, "Check", "Questions", new {id = @ViewBag.id, reponse = @mot}, new AjaxOptions()
                                        {
                                            HttpMethod = "GET",
                                            UpdateTargetId = "cor",
                                            InsertionMode = InsertionMode.Replace,

                                            OnComplete = "disablelink"
                                        }, new
                                        {
                                            @class = "b",
                                            @style = "text-decoration: none"
                                        })</div>

            }*@
                        

                        @*retourner vers la liste des niveaux*@
                        @*<form action="/Niveaux/Index/" method="post">
                <input type="hidden" name="diff" value="@Session["diff"]"/>
                <input type="submit" value="Retour"/>
            </form>*@

                        <br>
                        <br>
                        <br>
                        @*quand il n y a pas de faute*@
                        @*<button class="w3-button b e w3-round-large  w3-xlarge">*@@Ajax.ActionLink("IL N'Y A PAS DE FAUTE", "Check", "Questions", new { id = @ViewBag.id, reponse = "none" }, new AjaxOptions()
                                                                           {
                                                                               HttpMethod = "GET",
                                                                               UpdateTargetId = "cor",
                                                                               InsertionMode = InsertionMode.Replace,

                                                                               OnSuccess = "disablelink"
                                                                           }, new { @class = "c w3-button  w3-round-large  w3-xlarge", @style = "text-decoration:none" })@*</button>*@
                                                                        <br>
                                                                        <br>

</div>
            </div>
      
    
            <!-- End Middle Column -->
        </div>
    
        <!-- Right Column -->
        <div class="w3-col m2">
            <div class="w3-card-2 w3-round w3-white w3-center"></div>
            <br>
            <br>
            <!-- End Right Column -->
        </div>
    
        <!-- End Grid -->
    </div>

    <!-- End Page Container -->
</div>

QUIZZ/Voltaire/Views/Questions/Suivant.cshtml
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">


    function disablelink() {

        $(".b").removeAttr("href");
        
    };

</script>

@model String[]
@{
    Layout = "~/views/shared/_LayQ.cshtml";
}

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
    <!-- The Grid -->
    <div class="w3-row">
        <!-- Left Column -->
        <div class="w3-col m3">
            <!-- Profile -->
            <div class="w3-card-2 w3-round w3-white">
                <div class="w3-container w3-padding">
                    <h4 class="w3-center">Ayoub Bennouna</h4>
                    <p class="w3-center"><img src="~/Content/img/3.png" style="height:106px;width:106px" alt="Avatar"></p>
                    <hr>
                    <p><em class="fa fa-pencil fa-fw w3-margin-right w"></em>Etudiant</p>
                    <p><em class="fa fa-home fa-fw w3-margin-right w"></em> Rabat,Agdal</p>
                    <p><em class="fa fa-birthday-cake fa-fw w3-margin-right w"></em> Mai 18, 1995</p>
                </div>
            </div>
            <br>

            <!-- Accordion -->
            <div class="w3-card-2 w3-round">
                <div class="w3-white">
                    <div id="Demo1" class="w3-hide w3-container">
                        <p>Some text..</p>
                    </div>
                    <div id="Demo2" class="w3-hide w3-container">
                        <p>Some other text..</p>
                    </div>

                </div>
            </div>
            <br>

            <!-- Interests -->
            <div class="w3-card-2 w3-round w3-white w3-hide-small"></div>
            <br>

            <!-- Alert Box --><!-- End Left Column -->
        </div>

        <!-- Middle Column -->
        <div class="w3-col m8">

            <div class="w3-row-padding">

                <div class="w3-card-4 w3-round w3-white w3-padding e w3-padding-24 w3-margin-left w3-center">
                    <br>
                    <br>
                    <br>
                    @foreach (var mot in Model)
                    {
                        <span class="w3-xlarge b ">@mot</span>
                    }

                    <br/>
                    <br/>
                    <hr/>
                    <div id="cor"></div>
                    @for (int i = 0; i < 6; i = i + 2)
                    {

                          
                        <div class="w3-xlarge b">
                            @Ajax.ActionLink(@Model[i], "Check", "Questions", new { id = @ViewBag.id, reponse = @Model[i] }, new AjaxOptions()
                            {
                                HttpMethod = "GET",
                                UpdateTargetId = "cor",
                                InsertionMode = InsertionMode.Replace,

                                OnComplete = "disablelink"
                            }, new
                            {
                                @class = "c w3-button  w3-round-large w3-margin",
                                @style = "text-decoration: none;width:200px"
                            })
                        </div>
                               
                           

                     

                    }
                    @*retourner vers la liste des niveaux*@
                    @*<form action="/Niveaux/Index/" method="post">
                            <input type="hidden" name="diff" value="@Session["diff"]"/>
                            <input type="submit" value="Retour"/>
                        </form>*@

                    <br>
                    <br>
                    <br>
                    @*quand il n y a pas de faute*@
                    @*<button class="btn e w3-round-large b w3-xlarge">*@
                        @Ajax.ActionLink("IL N'Y A PAS DE FAUTE", "Check", "Questions", new { id = @ViewBag.id, reponse = "none" }, new AjaxOptions()
                   {
                       HttpMethod = "GET",
                       UpdateTargetId = "cor",
                       InsertionMode = InsertionMode.Replace,

                       OnSuccess = "disablelink"
                   }, new { @class = "c btn  w3-round-large  w3-xlarge", @style = "text-decoration:none" })
                    @*</button>*@
                    <br>
                    <br>

                </div>
            </div>


            <!-- End Middle Column -->
        </div>

        <!-- Right Column -->
        <div class="w3-col m2">
            <div class="w3-card-2 w3-round w3-white w3-center"></div>
            <br>
            <br>
            <!-- End Right Column -->
        </div>

        <!-- End Grid -->
    </div>

    <!-- End Page Container -->
</div>